REM INSERTING into ICAPE.CTK_CARRIERS
SET DEFINE OFF;
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Apm',25);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Marsmery',103);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Mega Coach',123);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Pioneer Coaches',163);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Fun Lover Coaches',203);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Tombs Motors',284);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,null,33);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Greyhound Express',43);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Citiliner Plus',143);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Citiliner Plus Malawi Carrier',183);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Munenzwa',303);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Margate Mini Coach Carrier',363);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Greyhound Mega Coach',223);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Luciano',243);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Transit Liner',283);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values ('R','SA Roadlink',1);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values ('P','Pioneer / Phadziri',2);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values ('M','Intercape',3);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values ('G','Greyhound',4);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values ('g','Citiliner',5);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values ('X','Intercity Express',6);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values ('S','Intercape Sleepliner',7);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values ('T','Translux',8);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values ('t','City to City',9);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values ('I','Margate Mini Coach',10);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values ('C','Chihwa Tours',11);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values ('H','Hawk Coaches',12);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values ('A','Atlantic',13);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values ('U','Munorurama',14);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values ('N','Netshituni / Nyamende',15);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values ('e','Eagle Liner',16);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values ('L','Aluane Luxury Coaches',17);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values ('a','APM',18);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values ('O','Eldo',19);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Mybus',27);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Atlantic Charters And Tours',30);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values ('D','DMJ Transport',20);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values ('J','Jr Choeu',21);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Eldo Coaches',23);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Dmj Transport',24);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Greyhound Budget',26);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Nozulu',28);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Shalom Bus Services',29);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Delta Coaches',31);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'City To City',32);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Greyhound Dreamliner',63);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Business Time Express',83);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'African Grey',263);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Intercape Budgetliner',323);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Chilwans Express',343);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'A P M',383);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Ilulabus',504);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Wezwe Coaches',544);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Mavumisa Transport',624);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Greyhound Premium',824);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Vilamora Xpress Africa (pty) Ltd',403);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Vilamora',483);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Luvalo Brothers Transport',484);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Jobela Star',524);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Lamavuso',604);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Bhekizizwe',684);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Citi Link',764);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Mulaudzi',804);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Greyhound Lite',825);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Hartley Tours',443);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'K K Coaches',564);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Badela',584);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Apm Wc',644);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Big Tree Coaches',664);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Ll Vaya Africa',704);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Nobles Transport',784);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Apmwc',423);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Vilamora Intercity',463);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Fortune Bus',724);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Williams Coaches',744);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Katiso',844);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Makalala Transport',904);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Jacobs Coaches',944);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Intercape Inter-Connect',965);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Eagle Liner Transport',1004);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Big Sky Intercity',966);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Gasela',864);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'F F Gertse',884);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Intercape Mainliner',964);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Flexi City Connect',1044);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Zululand Bus Services',924);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Intercity Xpress',984);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Southern Shuttle',1024);
Insert into ICAPE.CTK_CARRIERS (CODE,NAME,SERIAL) values (null,'Margate Coach',1025);
