<?
/* ************************************************************* */
/* *********** Removed styles for context ment ***************** */
/* ************************************************************* */
?>
<style>
  .menuItem {cursor: hand; font-family:Arial;font-size:8pt;
            width:180;padding-left:20;background-Color:menu;color:black}
  .highlightItem {cursor: hand; font-family:Arial;font-size:8pt;
             width:180;padding-left:20;background-Color:highlight;color:white}
</style>
