<html>
	<head><link type="text/css" rel="stylesheet" href="style.css"><title>Job Card Items</title></head>
	
	<body>
	<? VV("nomenu");  if ($nomenu!="Y") require_once ( "menu.inc" ); else $cookiecompany=0; ?>
    <?
	require_once("error.inc");
    	require_once("serial.inc");
	require_once("../php3/oracle.inc");
    	//require_once("../php3/logs.inc");
    	require_once("../php3/misc.inc");
    	require_once("../php3/sec.inc");
	VV("cs");
	VV("source");
	VV("cnumber");
	VV("coach");
	VV("jobcardserial");
	VV("other");
	VV("cat_select");
	VV("comments");
	VV("mynotes");

	if (!isset($stage))
		$stage = 0;
	VV("oldtab");

	$results = array();
	

	if( !open_oracle() )
		exit;

//    if( !AllowedFlag("MOVE_JOBCARDS" ) && !AllowedFlag("MOVE_ALL" )  )
 //  	access( __FILE__ );
	
	get_serial(getenv("REMOTE_USER"));
	?>
	<script language="JavaScript">
        function checkLen( target, size ) {
        	if( target.value.length > size ) {
            	target.value = target.value.substring(0,size);
            }
        }
	</script>
	<?
		
	
	if( $stage==0 ) {
		exit;
	}
	elseif( $stage==1 ) {
		?>
		<div class="info">
			This screen allows you to add a fault to a single vehicle or multiple vehicles. The fault is added to each vehicle selected, and
			the next time a job card is opened for that vehicle the fault will appear on that job card.
		</div>
		<script>
			function updatefaults() {
				document.getElementById('myframe').src='fault_iframe.phtml?vehicle='+document.getElementById('coach').value;
			}
		</script>
		<br>
		<form name="standard" method="post" action=newadhocitem.phtml enctype="multipart/form-data">
		<input type="hidden" name="stage" value="11">
		<input type="hidden" name="cnumber" value="<?=$cnumber?>">
		<input type="hidden" name="MAX_FILE_SIZE" value="1000000">
		<h3>An ad hoc fault</h3>
<?
                if ($oldtab=="Y")
                        include("pick_fault_old.phtml");
                else
                        include("pick_fault.phtml");

?>

		<table width=95%>
			<tr class="cell">
				<td width=150>Vehicle/s</td>
				<td><input type=text id=coach name=coach size=10 maxlength=10 onkeyup='updatefaults();' value='<?=$coach?>'> 
					<select onChange='coach.value=this.value; updatefaults(); '>
					<?
					$results = array();
					ora_parse( $cursor, "SELECT serial, code, reg_no, is_current FROM VEHICLES WHERE is_current='Y' AND rented<>'Y' ORDER BY code, reg_no" );
					ora_exec( $cursor );
					
					while( ora_fetch_into( $cursor, $results ) ) {
						print "<option value=\"$results[1]\"";
						if ($results[0]==$cs)
							echo " SELECTED";
		
						print ">$results[1] --> $results[2]";
						$results = array();
					}
					?>
					</select><?
					 if( AllowedFlag("MOVE_JOBCARDS" ) || AllowedFlag("MOVE_ALL" )  ) :

/*
					?>
					 or
					<select name='cat_select'>
						<option value=''>Select a Category</option>
						<option value='r'>All Cars</option>
						<option value='c'>All Coaches</option>
						<option value='b'>All Vans</option>
						<option value='o'>All Combies</option>
						<option value='h'>All Hysters</option>
					</select>
					<?
*/
						endif;
					?>	
				</td>
				<script language=JavaScript> try { document.forms[0].elements[2].focus() }  catch (error) {}; </script>
			</tr>
			<tr class="cell">
				<td>Fault Picture</td>
				<td><input type="file" name="faultpicture"></td>
			</tr>
		</table>
		<br>
<?
		echo "<input type=hidden name=source value='$source'>";
?>
		<div id=submit><input type="submit" value="Add This Item" >
		</div>
		<?  echo "<input type=hidden name=nomenu value='$nomenu'>"; ?>
		</form>
		<?
	}
	elseif( $stage==11 ) {
                if ($fault[0]=="f")
                        $fault=substr($fault,1,999);
                if ($fault[0]=="o") {
                        $other=true;
                        $faultserial=substr($fault,1);
                } elseif ($other=="Y") {
                        $other=true;
                        $faultserial=$fault;

                } else {
                        $other=false;
                        $faultserial=$fault;
                }
                if (!is_numeric($faultserial) || ($faultdescription=="" && $other)) {
                        echo "Please go back, select a fault and provide a description ($fault)";
                        echo "<form method=post><input type=button value='Go Back' onClick='history.go(-1);'></form>";

                        exit;
                }
                $fault=$faultserial;

                // TO DISABLE THE CREATING OF NEW ENTRIES, DISABLE THIS NEXT BLOCK OF CODE
                if ($other) { // create new entry
                        ora_parse($cursor, "select tfc_id_seq.nextval from dual");
                        ora_exec($cursor);
                        ora_fetch($cursor);
                        $newfault=getdata($cursor,0);
                        $oldfault=$faultserial;

                        $faultdescription=str_replace("'","",$faultdescription);
                        $shortname1=substr($faultdescription,0,200);
                        $shortname2=substr($faultdescription,0,2000);
                        ora_parse($cursor,"insert into technical_faults_category (tfc_id, tfc_ref_category, tfc_name, tfc_description, tfc_is_deleted, tfc_is_other) values ($newfault, $oldfault, '$shortname1', '$shortname2', 0, 1)");
                        if (ora_exec($cursor)) {
                                $fault=$newfault; // switch to the newly created category
                        }
                }


		if( $faultpicture=="none" || empty( $faultpicture ) )
			$picture = "N";
		else $picture = "Y";
		
		if ($cat_select != ""){
			
			
		
		}else{
		
			$coach = trim( strtoupper( $coach ) );
		
		}
		$comments = str_replace( "\'", "''", $comments );
		$faultdescription = str_replace( "\'", "''", $faultdescription );
		$reporteddate = date( "d/m/Y H:i:s" );
		$first = true;
		$firstserial = -1;
		
		$cur2 = ora_open( $conn );
		$cur3 = ora_open( $conn );
		
		
	   	if ($cat_select != ""){
	   		
	   		$qry = "SELECT serial,code FROM VEHICLES WHERE class='$cat_select' AND is_current='Y' AND rented<>'Y'";}
	   	else{
	   	
	   		$qry = "SELECT serial,code FROM VEHICLES WHERE code='$coach' AND is_current='Y' AND rented<>'Y'";
	   	}
	   	ora_parse($cursor, $qry);
	   	ora_exec( $cursor);
	   	//echo $qry;
	   	
	   	
	   	$is_rows = false; $count = 0;

	   	while (ora_fetch_into($cursor, $row, ORA_FETCHINTO_ASSOC)){ 

	   		$is_rows = true;
	   		
	   		$count++;
	   		
	   		$coacha = $row['SERIAL'];
			$coachname = $row['CODE'];
			
	   		$qry = "SELECT MOVE_ITEMS.nextval FROM dual";
	   		ora_parse( $cur2, $qry );
    			ora_exec( $cur2 );
    			$itemserial = ora_getColumn( $cur2, 0 );
			$us=getuserserial();
			if (is_numeric($cnumber)) {
				$rcomments="C$cnumber";
			}
    			
			$faultdescription=str_replace("'","",$faultdescription);
			$rcomments=str_replace("'","",$rcomments);
			if (!is_numeric($fault))	
				$fault="null";
			ora_parse($cur3,"select jobcardserial, depot, jobopendate, jobopenwho from move_jobs where unitserial=$coacha and type=1 and jobclosedate is null order by jobcardserial desc");
			ora_Exec($cur3);
			if (ora_fetch($cur3)) {
					$jobcard = getdata($cur3, 0);
					$mynotes .= "$coachname: This has been added to MOVE$jobcard in ".getdata($cur3,1)." opened by ".getdata($cur3,3)." on ".getdata($cur3,2)."<bR>";
					// TODO : mail to the person who opened the jobcard
					$opened_by=getdata($cur3,3);
					ora_parse($cur3,"select email from user_Details where username='$opened_by' and is_Current in ('Y','L')");
					ora_Exec($cur3);
					$opened_by.="@cavmail.co.za";
					if (ora_fetch($cur3)) {
						if (getdata($cur3,0)!="")
							$opened_by=getdata($cur3,0);
					}
					mail($opened_by,"New fault for $coachname",getenv("REMOTE_USER")." just added an ad-hoc item to MOVE$jobcard ($coachname): $faultdescription");
			} else {
					$jobcard = 0;
					$mynotes .= "This will be added to the NEXT jobcard opened for $coachname<br>";
			}
			$statement = "INSERT INTO MOVE_JOBCARDITEMS ( itemserial, jobcardserial, unitserial, reportedwho, reporteddate, faultclass, faultdesc, faultpicture, type, faultvalid, statusengineer,reportcomments, fault_category ) ";
			$statement .= "VALUES( $itemserial, $jobcard, '$coacha', '$REMOTE_USER', to_date( '$reporteddate', 'DD/MM/YYYY HH24:MI:SS' ), $faultclass, '$faultdescription', '$picture', '1', 'N', 'Z', '$rcomments', $fault )";
//			echo "$statement<br>";
			
			ora_parse( $cur3, $statement );
			
    			if( !ora_exec( $cur3 ) )showError( __FILE__, __LINE__, "$stage", "$statement<br><br>Could not add item" );
			elseif (is_numeric($cnumber)) {
				$qry="insert into logged_call_notes values ( to_date( '$reporteddate', 'DD/MM/YYYY HH24:MI:SS' ), 'M', $us,'$faultdescription'
,$cnumber)";
                                ora_parse($cur3,$qry);
                                ora_exec($cur3);


			}
		
			if( $picture=="Y" ) {
				
				if( $first ) {
					
					$firstserial = $itemserial;
				
					if (is_uploaded_file($_FILES['faultpicture']['tmp_name'])) {
						if( !move_uploaded_file($_FILES['faultpicture']['tmp_name'], "/usr/local/www/pages/move/uploads/$itemserial") ) {
							showError( __FILE__, __LINE__, "$stage", "Could not upload file" );
						} else chmod( "/usr/local/www/pages/move/uploads/$itemserial", 0666 );
					}
				
					$first = false;
					
				} else {
					if( $firstserial == -1 ) mail( "keith@intercape.co.za", "MOVE Error", "$firstserial is -1" );
					
    	    				if( link( "/usr/local/www/pages/move/uploads/$firstserial", "/usr/local/www/pages/move/uploads/$itemserial" ) ) {
    	    					chmod( "/usr/local/www/pages/move/uploads/$itemserial", 0666 );
    	    				} else showError( __FILE__, __LINE__, "$stage symlink", "Hard linking failed" );
    	    				
    	    			}
			}
				
			//else showError( __FILE__, __LINE__, "$stage", "SOB...." );    
			
		}			
	   		

	   	
	   	if( $is_rows == false ) {
			if ($coach=="")
				$coach="a vehicle (did you specify one?)";
	   		print "Could not find <u>$coach</u>. Click <a href='#x' onClick='history.back();'>here</a> to go back.";
	   		exit;
	   	}
	   	
	}	//<script language="JavaScript"> temp.submit() </script> 
	
	if (isset($count)) {
	if ($count>0)
		echo "<b><font color='red'>$count</font></b> <b>vehicle/s  have been affected.<hr>$mynotes<hr></b>";
	else
		echo "<b><font color=red size=+2>STRANGE....  NOTHING DONE....</font></b>";
	}

	if ($nomenu!="Y")
	echo "<p><a href='newadhocitem.phtml?stage=1'>Return</a>";

	if (is_numeric($cnumber)) 
		if ($source=="OTR")
			echo "<p><a href='logged_calls.phtml?stage=4&srl=$cnumber'>Back to to C$cnumber</a><p>";
		else
			 echo "<p><a href='/booking/logged_calls.phtml?stage=4&srl=$cnumber'>Back to to C$cnumber</a><p>";

//	else 	echo "($cnumber)";
		
	?> 
	<form name="temp" method="post" action="newadhocitem.phtml"><input type="hidden" name="cnumber" value="<?=$cnumber?>"><input type="hidden" name="stage" value="1"><input type=hidden name=coach value='<?=$coach?>'><input type="hidden" name="jobcardserial" value="<?=$jobcardserial?>"></form>

<iframe id=myframe name=myframe width=100% height=800></iframe>
	</body>
</html>
