<html>
	<head><link type="text/css" rel="stylesheet" href="style.css"><title>PICK FAULT</title><head>
	
	<body>
	<?
   // require_once("error.inc");
  //  require_once("stock.inc"); // this might not be needed
    require_once("../php3/oracle.inc");
    require_once("../php3/sec.inc");
    require_once("../php3/misc.inc"); 

    if( !open_oracle() )
    	exit;

	if( !AllowedAccess( "" ) )
		exit;

echo date("H:i:s")."<br><a href=keith/pickfault1.phtml>Old Tablet version</a><br>";
?>
<input type=button onclick='document.location.reload(true);' value='Reload'>  
<input type=button onclick="document.getElementById('debug').style.display='none';"  value='Test'>

<input type=button onclick="document.getElementById('debug').style.display='block';"  value='Test2'>

<input name=debug value='0' id=debug size=80>
<div id=debug2>Debug2</div>
<script>
	try {
	document.getElementById('debug2').innerHTML='A';
	} catch(error) {} 
	try { document.getElementById('debug').value='1';
	} catch (error) { }
	var lastshown = -1;
	var faultSupplied = false;

	function showgroup(group, parents, haskids) {
		try {
			document.getElementById('f' + lastshown).style.background = '#CCCCCC';
		} catch (error) { }

			let found = false;
		try {
			parents.forEach( element => { 
				console.log('compare ' + element + ' to ' + lastshown); 
				if (element == lastshown) {
					found = true; 
				}
			});	
		} catch (error) {} 

			if (!found) {
//				console.log('Removing ' + lastshown);
				try { 
				document.getElementById('group' + lastshown).style.display = 'none';
				} catch (error) {} 
			}
			try {
			document.getElementById('fo' + lastshown).style.background = '#CCCCCC';
			} catch (error) { }


		lastshown = group;
		try {
			document.getElementById('f' + group).style.background = 'lightblue';
		} catch (error) { }
		try {
			document.getElementById('group' + group).style.display = 'block'; 
		} catch (error) {
		}

//                document.getElementById('other').style.display = 'none';
		try {
		document.getElementById('rf' + group).checked = true;
		} catch (error) {}
		
		if (haskids) {
//			console.log('haskids');
		
			document.getElementById('notok').style.display = 'block';
			document.getElementById('ok').style.display = 'none';
			faultSupplied = false;
			document.getElementById('otherwarning').style.display = 'none';

		} else {
//			console.log('nokids');
			document.getElementById('ok').style.display = 'block';
                        document.getElementById('notok').style.display = 'none';
			faultSupplied = true;
			document.getElementById('otherfault').focus();
			otherstatus();
		}	


	}

        function useOther(group) {
                try {
                        document.getElementById('f' + lastshown).style.background = '#CCCCCC';
//			document.getElementById('group' + lastshown).style.display = 'none';
                        document.getElementById('fo' + lastshown).style.background = '#CCCCCC';
                }
                catch (error) {
                }
                lastshown = group;
                try {
                        document.getElementById('fo' + group).style.background = 'lightblue';
                } catch (error) {
                }

//		document.getElementById('other').style.display = 'block';
		document.getElementById('rfo' + group).checked = true;

		document.getElementById('notok').style.display = 'none';
		document.getElementById('ok').style.display = 'none';
		document.getElementById('otherfault').focus();
		faultSupplied = true;
		otherstatus();

        }


	function otherstatus() {

		console.log('LEN: ' + document.getElementById('otherfault').value.length);
		if (document.getElementById('otherfault').value.length>5) {
			document.getElementById('otherwarning').style.display = 'none';
			if (faultSupplied)
				document.getElementById('submit').style.display = 'block';
			else
				document.getElementById('submit').style.display = 'none';
		} else {
			document.getElementById('otherwarning').style.display = 'block';
			document.getElementById('submit').style.display = 'none';
		}
	}

</script>

<?

function process_tree($parent, $level, $parents) {
	global $fault, $childrenof;
	
	$gap = "";
	$gap2 = "";
	for ($a = 0; $a < $level; $a++) {
		$gap .= "&nbsp;&nbsp;&nbsp;";
		$gap2 .= " ";
	}
	$extragap = $gap . "&nbsp;&nbsp;&nbsp;";

	
	echo "$gap2<div id=group$parent";
	if ($parent != -1)
		echo " style='display: none'";
	echo ">\n";

	$parents[]=$parent;
	$parentstext=json_encode($parents);

	foreach( $childrenof[$parent] as $key => $serial)  {
		if (isset($childrenof[$serial])) {
			$haskids=1;
		} else {
			$haskids=0;
		}
		echo "$gap2  <div id='f$serial' style='background: #CCCCCC'  onclick='showgroup($serial, $parentstext, $haskids);'>". $gap . "<input type=radio name=fault id='rf$serial' value='f$serial'>" . $fault[$serial]["TFC_NAME"]."</div>\n";
		if (isset($childrenof[$serial]))
		{
			process_tree($serial, $level + 1, $parents); // recursively go down the tree
		}
	}
	if ($parent != -1) {
	        echo "$gap2  <div id='fo$parent'  style='background: #CCCCCC' onclick='useOther($parent);'>". $gap . "<input type=radio name=fault id='rfo$parent' value='fo$parent'>Other: " .$fault[$parent]["TFC_NAME"]."</div>\n";
	}


	echo "$gap2</div>\n";

}

		
ora_parse($cursor,"select * from technical_faults_category where tfc_is_deleted = 0  and tfc_is_other = 0");
ora_exec($cursor);
while (ora_fetch_into($cursor,$data,ORA_FETCHINTO_ASSOC)) {
	$fault[$data["TFC_ID"]]=$data;
	$parent=$data["TFC_REF_CATEGORY"];
	if ($parent=="")
		$parent=-1; // top level	
	$childrenof[$parent][]=$data["TFC_ID"];
	unset($data);
}

$level=0;
echo "<div id='toplevel'>";
$parents=array();
process_tree(-1,0, $parents);
echo "</div>";

echo "<div id='other'>Please type in details of fault: <input id='otherfault' onkeyup='otherstatus()' name=otherfault size=40></div>\n";
echo "<div id='otherwarning' style='display:none'><font color=red>PLEASE TYPE IN DESCRIPTION</font></div>";
echo "<div id=notok><font color=red>Please select a fault</font></div>";
echo "<div id=ok style='display: none'><font color=green>A fault has been selected</font></div>";
echo "<div id=submit style='display: none'><input type=submit value='Click here to add'></div>";


	close_oracle();
?>
<script>
try {
document.getElementById('debug').value='proper';
} catch (error) {}

</script>
</body>
</html>

