<?php

namespace Intercape\AgentPortalMailer;

define('FPATH', dirname(__FILE__).DIRECTORY_SEPARATOR);

require_once("../php3/oracle.inc");
open_oracle();

/**
 * Parses a csv file into a multidimensional array
 * where $data[''headers'] is the headers, and $data['rows'] is the rows
 * 
 * @param string $filename - The csv file, this must be full path of the file
 * @return array multidimensional array with 'headers' and 'rows'
*/
function parseCSV($filename){
    $data = [
        'headers' => null,
        'rows' => []
    ];

    if (($handle = fopen($filename, "r")) !== FALSE) {
        
        $data['headers'] = fgetcsv($handle, 1000, ",");

        while (($row = fgetcsv($handle, 1000, ",")) !== FALSE) {
            $data['rows'][] = $row;
        }

        fclose($handle);
    }

    return $data;
}

class Mail{
    public $from;
    public $to = [];
    public $cc = [];
    public $subject;
    public $message;
    public $attachments = [];

    private $body;

    function add_attachment($filename, $attachment_name){
        $this->attachments[$attachment_name] = $filename;
    }

    function send(){
        $this->body .= "--boundary\r\n";
        $this->body .= "Content-Type: text/html; charset=utf-8\r\n";
        $this->body .= "Content-Transfer-Encoding: base64\r\n\r\n";
        $this->body .= chunk_split(base64_encode($this->message));

        foreach ($this->attachments as $attachment_name => $filename){
            $attachment = chunk_split(base64_encode(file_get_contents($filename)));
            $ext = pathinfo($filename, PATHINFO_EXTENSION);

            $this->body .= "--boundary\r\n";
            $this->body .= "Content-Type: text/csv; name=\"" . basename($filename) . "\"\r\n";
            $this->body .= "Content-Transfer-Encoding: base64\r\n";
            $this->body .= "Content-Disposition: attachment; filename=\"" . "$attachment_name.$ext" . "\"\r\n\r\n";
            $this->body .= $attachment;
        }

        $this->body .= "--boundary--";

        $headers = "MIME-Version: 1.0\r\n";
        $headers .= "Content-Type: multipart/mixed; boundary=\"boundary\"\r\n";

        if ($this->from){
            $headers .= "From: {$this->from}\r\n";
        }

        if (!empty($this->cc)){
            $headers .= 'CC: '.implode(', ', $this->cc);
        }

        if (mail(implode(', ', $this->to), $this->subject, $this->body, $headers)){
            return true;
        } else {
            $error = error_get_last();
            return false;
        }
    }
}

$agent_portal_link = 'https://secure.intercape.co.za/booking/invoices.phtml';

$mail = new Mail();
$mail->from = $noreply_email;
$mail->cc = [];
$mail->message = "<p style='font-family: 'Georgia', serif; font-size: 18px; letter-spacing: 0.5px; line-height: 1.6; color: #333; margin: 20px 0; padding: 10px;'>Good day
<br><br>
Hope you are well. 
<br><br>
Please note that your weekly statement can now be downloaded from the agent portal with link<br>
<a href='{$agent_portal_link}'>Agent Portal Link.</a>
<br><br>
Kindly email your proof of payment and remittance to <a href='mailto:debtors@intercape.co.za'>debtors@intercape.co.za</a>.
<br><br>
Please do not reply to this mail.
<br><br>
Kind regards,<br>
Intercape Debtors Controllers</p>";

$filename = '/usr/local/www/DEBTORS_INFO.csv';

$exist = file_exists($filename);

if (file_exists($filename)){
    $data = parseCSV($filename);

    if (!empty($data)){

        foreach ($data['rows'] as $row){
            list($account_code, $email) = $row;

            $mail->subject = "{$account_code} - Weekly Statement";
            $mail->to = [$email];

            if (!$mail->send()){
                $error = error_get_last();
            }
        }
    }
}

?>
