<html>
	<head><link type="text/css" rel="stylesheet" href="style.css"><title>OC Vehicles <?=$cookiedepot?></title><head>
	
<?

for ($a=1;$a<24;$a++)
	if ($a<12)
		$times[$a]="$a"."am";
	elseif ($a==12)
		$times[12]="noon";
	else { $b=$a-12; $times[$a]=$b."pm"; }


require_once("../php3/opstimes.inc");
function go_back()
{
        echo "<form>";
        echo "<input type=button value='Go Back' ";
        echo "onclick='javascript:history.back()'>";
        echo "</form>";
}

    require_once("error.inc");
    require_once("../php3/oracle.inc");
    //require_once("../php3/logs.inc");
    require_once("../php3/misc.inc");
    require_once("../php3/sec.inc");

	require_once ("menu.inc");

   if( !open_oracle() )
    	exit;


    	
    if (!AllowedFlag("MOVE_COACH"))
	    if( !AllowedFlag("FOREMAN" ) )
		    if( !AllowedAccess("FLAG_OC" ) )
	
			exit;
	



		?>
		<div class="choices">
	    <table class="choices">
	    	<tr bgcolor=white>
	    		<td width=200><a href="oc.phtml?stage=0">Currently OC Vehicles</a></td>
	    		<td width=200><a href="oc.phtml?stage=1">Flag vehicle as OC</a></td>
	    	</tr>
	    </table>
	    </div>
	    <br>
		<?
	if( $stage==0 ) { // list OC coaches

		$today = date( "Ymd");

		ora_parse( $cursor, "SELECT B.code, A.start_date, A.end_date, A.notes, A.entry_serial, A.time_ready, to_char(A.flagged_date,'DD Mon YYYY HH24:MI:SS')  FROM vehicle_oc A, vehicles B WHERE A.vehicle = B.serial AND end_date >= $today AND replaced_by IS NULL ORDER BY code");
		ora_exec( $cursor);
		echo "<table>";
		echo "<tr class=title><td colspan=10><b><center>Vehicles currently out of commission</td></tr>";
		echo "<tr class=title><td>Vehicle</td><td>From</td><td>Until</td><td colspan=2>Click to change</td><td>Notes</td><td>When</td></tr>";
		$line=0;
		unset( $data);
		while( ora_fetch_into( $cursor, $data)) {
			$line++;
			if ( $line % 2 == 0)
				echo "<tr class=cell>";
			else
				echo "<tr class=altcell>";
			$data[1] = afrikdate( $data[1]);
			$data[2] = afrikdate( $data[2]);
			echo "<td nowrap>$data[0]</td><td nowrap>$data[1]</td><td nowrap>$data[2] @".$times[$data[5]]."</td><td nowrap><a href=oc.phtml?stage=3&srl=$data[4]>Back in action</a></td><td nowrap><a href=oc.phtml?stage=4&srl=$data[4]>change date</a></td><Td nowrap><font size=2>$data[3]</td><td>$data[6]</td></tr>";
			
			unset( $data);
		} // while
		echo "</table>";
		if ($line==0)
			echo "No vehicles are currently marked OC";

	} // stage 0
	elseif ( $stage == 1) {
		$today = date( "Ymd");
		echo "<form method=post action=oc.phtml><input type=hidden name=stage value=2>";
		ora_parse( $cursor, "SELECT A.serial, A.code FROM vehicles A WHERE is_current='Y' AND serial NOT IN ( SELECT vehicle FROM vehicle_oc WHERE replaced_by IS NULL AND end_date >= $today and cleared_date is null  ) ORDER BY code");
		ora_exec( $cursor);
		echo "Vehicle: <select name=vehicle>";
		unset( $data);
		while( ora_fetch_into( $cursor, $data)) {
			echo "<option value='$data[0]'>$data[1]</option>";
			unset( $data);
		} // while
		echo "</select>";
		$today = nextdate( $today, 3);
		echo "<br>Flag as OC from <input name=startd size=8 value='$today' maxlength=8> until <input name=last size=8 value='$today' maxlength=8> at <select name=time>".makeselect2($times,12)."</select>";		
		echo "<br>Reason/Notes: <input name=notes size=80 naxlength=100><Br>";
		
		echo "<input type=submit value='Flag as Out Of Commission'>";
	} // stage 1 - mark a vehicle (part 1)
	elseif ( $stage==2 ) {
		$startd=trim($startd);
		$last=trim($last);
		if (strlen($startd)!=8 || strlen($last)!=8 || !is_numeric($startd) || !is_numeric($last)) {
			echo "<font color=red><h2>Sorry, you did not put in a valid date</h2></font>";	
			exit;
		}
		
		$us = getuserserial();
		ora_parse( $cursor, "SELECT oc_serial.nextval FROM DUAL");
		ora_exec( $cursor);
		ora_fetch( $cursor);
		$ser = ora_getColumn( $cursor, 0);
		$today = date( "Ymd");
		$startdate = date( "Ymd His");
		// first check to make sure it doesnt overlap an existing entry...

		ora_parse( $cursor, " SELECT start_date, end_date from vehicle_oc where vehicle=$vehicle and start_date<=$today and end_date>=$today and replaced_by is null and cleared_date is null");
		ora_exec( $cursor);
		unset( $data);
		if (ora_fetch_into( $cursor, $data)) {
			
			$data[0]=afrikdate($data[0]);
			$data[1]=afrikdate($data[1]);
			echo "Sorry, that vehicle/trailer is already flagged as OC from $data[0] to $data[1]!<Br>";	
			exit;
		}
		$qry = "INSERT INTO vehicle_oc ( entry_serial, vehicle, flagged_by, start_date, end_date, notes, flagged_date, time_ready) VALUES ( $ser, $vehicle, $us, $startd, $last, '$notes', to_date( '$startdate', 'YYYYMMDD HH24MISS' ), $time)";
		
		ora_parse( $cursor, $qry);
		if ( !ora_exec( $cursor))		
			echo "ERROR: $qry<br>";
		else
		{
			echo "Done! <b>Please inform the OPS ROOM</b><hr>";
					
			ora_parse($cursor,"select code from vehicles where serial=$vehicle");
			ora_Exec($cursor);
			ora_fetch($cursor);
			$vcode=getdata($cursor,0);

			$msg="  Vehicle $vcode has been flagged as O/C from $startd to $last ($notes)\n";
			ora_parse($cursor,"select rundate, info from ops_info where serial_no='$vehicle' and entry_type in ('c','t') and rundate>=$startd and rundate<=$last");
			ora_exec($cursor);
			while (ora_fetch($cursor)) {
				$line="  Currently rostered for ".getdata($cursor,1)." on ".getdata($cursor,0)."\n";
				echo "<font color=red><b>$line</b></font><bR>";
				$msg.=$line;
			}
			mail("johanvr@intercape.co.za,philipn@intercape.co.za,asnijman@intercape.co.za,keith@intercape.co.za,ernestl@intercape.co.za,ptafleetcontrol@intercape.co.za,steven@intercape.co.za,glennf@intercape.co.za","Bus flagged as O/C",$msg);
			
		}

	} // stage=2 - part 2 of mark a vehicle 

	elseif ( $stage ==3 ) { // put vehicle back into action
		$today = prevdate(date( "Tmd"));
		$us = getuserserial();
		$finishdate = date( "Ymd His");
		ora_parse( $cursor, "update vehicle_oc SET end_date=$today, cleared_by=$us, cleared_date=to_date( '$finishdate', 'YYYYMMDD HH24MISS' ) WHERE entry_serial=$srl AND replaced_by is null");
		ora_exec( $cursor);
		if ( ora_numrows( $cursor) == 1)
			echo "Done!";
		else
			echo "Sorry, there was a problem!";

	} // stage 3 - back in action
	elseif ( $stage == 4) { // change end date part 1
		echo "<form method=post action=oc.phtml><input type=hidden name=stage value=5>";
		ora_parse( $cursor, " SELECT * FROM vehicle_oc WHERE entry_serial = $srl");
		ora_exec( $cursor);
		unset( $data);
		if ( !ora_fetch_into( $cursor, $data)) {
			echo "Sorry, that entry was not found!!!<br>";
			exit;
		}
		ora_parse( $cursor, "SELECT code FROM vehicles WHERE serial=$data[1]");
		ora_exec( $cursor);
		if (ora_fetch( $cursor)) {
			echo "Vehicle: ".getdata($cursor,0)."<br>";
		}
		if (is_numeric($data[3]) || is_numeric($data[7])) {
			echo "Sorry, that entry cannot be changed!!!<br>";
                        exit;
		}
		echo "Start Date: <input name=startd size=8 maxlength=8 value='$data[4]'> End Date: <input name=end size=8 maxlength=8 value='$data[5]'> at <select name=time>";
		echo makeselect2($times,$data[10]);
		echo "</select> <br>";

		echo "Notes/Reason: <input name=notes value='$data[6]' size=80 maxlength=100><br>";
		echo "<input type=hidden name=srl value=$srl>";
		echo "<input type=submit value='Change Date/Time'>";
	} // stage 4 - change end date part 1
	elseif ( $stage == 5) {
		$startd=trim($startd);
                $end=trim($end);
                if (strlen($startd)!=8 || strlen($end)!=8 || !is_numeric($startd) || !is_numeric($end)) {
                        echo "<font color=red><h2>Sorry, you did not put in a valid date</h2></font>";
                        exit;
                }

                ora_parse( $cursor, " SELECT * FROM vehicle_oc WHERE entry_serial = $srl");
                ora_exec( $cursor);
                unset( $data);
                if ( !ora_fetch_into( $cursor, $data)) {
                        echo "Sorry, that entry was not found!!!<br>";
                        exit;
                }
                ora_parse( $cursor, "SELECT code FROM vehicles WHERE serial=$data[1]");
                ora_exec( $cursor);
                if (ora_fetch( $cursor)) {
                        echo "Vehicle: ".getdata($cursor,0)."<br>";
                }
                if (is_numeric($data[3]) || is_numeric($data[7])) {
                        echo "Sorry, that entry cannot be changed!!!<br>";
                        exit;
                }
		$allcorrect = true;
		unset($newser);
		ora_parse( $cursor, "SELECT oc_serial.nextval FROM DUAL");
		ora_exec( $cursor);
		ora_fetch( $cursor);
		$newser = ora_getColumn( $cursor, 0);
		if ( !is_numeric( $newser))
			$allcorrect = false;	

		$qry = "UPDATE vehicle_oc SET replaced_by=$newser WHERE entry_serial=$srl";
		ora_parse( $cursor, $qry);
		if ( !ora_exec( $cursor)) {
			echo "Error: $qry<Br>";
			$allcorrect = false;
		}
		unset ($us);
		$us = getuserserial();
		if ( !is_numeric($us))
			$allcorrect = false;

		$today = date( "Ymd");
		$startdate = date( "Ymd His"); 

               $qry = "INSERT INTO vehicle_oc ( entry_serial, vehicle, flagged_by, start_date, end_date, notes, flagged_date, time_ready) VALUES ( $newser, $data[1], $us, $startd, $end, '$notes', to_date( '$startdate', 'YYYYMMDD HH24MISS' ), $time)";

                ora_parse( $cursor, $qry);
                if ( !ora_exec( $cursor))
                        echo "ERROR: $qry<br>";
                else
                        echo "Done! <b>Please inform the OPS ROOM</b>";

	} // change end date - part 2
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	?>
</form>
	</body>
</html>
