<?php



require_once("php3/oracle.inc");
require_once("php3/misc.inc");


if (!isset($conn))
	open_oracle();



function password_check($us,$username,$pw) {

  global $cursor;

  $return=array();
  $return[0]="0";
  $return[1]="<font color=red>WRONG</font>";

  $username=str_replace("'","",$username);
  $password=str_replace("'","",$pw);
  if ($us!="")
        if (!is_numeric($us))
		return $return;

  if ($us!="")
        ora_parse($cursor,"select is_current, password, bad_pw_counter from user_details where user_serial=$us");
  else
        ora_parse($cursor,"select is_current, password, bad_pw_counter from user_details where username='$username' order by is_current desc");
  ora_exec($cursor);

  if (!ora_fetch($cursor)) {
	return $return;	
  } else {
        $current=getdata($cursor,0);
        $hashed_password=getdata($cursor,1);
        $bad_counter=getdata($cursor,2);

        if ($current=="L") {
		$return[0]="L";
		$return[1]="<font color=red>LOCKED OUT: CALL HC</font>";
		return $return;
        } else {
                if (hash_equals($hashed_password, crypt($password,$hashed_password))) {
			$return[0]="1";
			$return[1]="<font color=green>CORRECT</font>";
                }
                else {
			return $return;
                }
        }
  }

return $return;

} // function

?>
