<?  if ($csv=="Y") {
	
		
        header( "Content-Disposition: inline; filename=drift.csv");
        header( "Content-Type: application/download; filename=\"drift.csv\"");

		ob_start();
	}

?><html>
<head>
<link rel="stylesheet" type="text/css" href="/booking/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/booking/css/dataTables.bootstrap.min.css">

</head>
<body leftmargin=3>
<link rel="stylesheet" type="text/css" href="driftstyle.css" />
<script src="/booking/js/jquery-3.5.1.min.js"></script>
<script src="/booking/js/jquery.dataTables.min.js"></script>
<script src="/booking/js/dataTables.bootstrap.min.js"></script>
<? require("../php3/context.inc"); ?>
<?
require("../php3/oracle.inc");
require("../php3/colors.inc");
require("../php3/logs.inc");
require("../php3/misc.inc");
require("../php3/sec.inc");

if (!open_oracle()) { Exit; };
if (!AllowedAccess("")) { Exit; };
get_colors(getenv("REMOTE_USER"));

echo "<div id='mainnav'><a href=drift_dates.phtml>Edit Dates</a>  <a href=drift_parameters.phtml>Edit Scenarios</a>  <a href=drift_globals.phtml>Edit Globals</a>  <a href=drift.phtml>DRIFT Forecast</a>  <a class=active href=drift_report_details.phtml>Route Details</font></a>  <a href=drift_report_details2.phtml>Date Details</a>  <a href=drift_report.phtml>Summary</a></div><hr>";
echo "<div style='padding: 5px'>";
echo "<a href=drift_report_details.phtml?csv=Y>Download as CSV</a><br>";
echo "<div id=tablediv style='width: 80%'>";
echo "<table class=ResultsTable id=mytable border=1 cellspacing=0 width='100%'>";
echo "<thead>";
echo "<tr><th>Time Period</th><th align=right>Scenario</th><th align=right>Depot</th><th align=right>Last Generated</th><th align=right>Route No</th><th align=right>Budgeted</th><th align=right>Actual</th><th align=right>Total</th></tr>";
echo "</thead><tbody>";

if ($csv=="Y") {
	ob_end_clean();
	echo "Time Period,Scenario,Depot,Last Generated,Route No,Budgeted,Actual,Total\n";
}
ora_parse($cursor,"select B.date_range_name,C.parameter_name, R.depot, R.last_generated, A.route_no, A.budgeted_trips, A.actual_trips, A.total_trips from drift_output_details A, drift_date_ranges B, drift_parameters C, drift_run R where R.run_id in (select max(run_id) from drift_run group by depot,time_period,scenario_no) and R.scenario_no=C.parameter_serial and C.active='Y' and R.time_period=B.date_range_serial and R.run_id=A.run_id order by R.depot, A.route_no, R.last_generated");
ora_exec($cursor);
while (ora_fetch_into($cursor, $data, ORA_FETCHINTO_ASSOC)) {
	$data["ROUTE_NO"]=sprintf("%04d", $data["ROUTE_NO"]);

	if ($csv=="Y") {

		foreach ($data as $key=>$val) 
			echo '"'.$val.'",';
		echo "\n";

	} else {
		echo "<tr><td>";
		echo implode("</td><td align=right>", $data);
		echo "</td></tr>";
	}
	unset($data);
}
if ($csv=="Y") {
	exit;
}

echo "</tbody></table>";
echo "</table>";

echo "</div>";

?>
</form>

<script>
$(document).ready(function() {
    console.log('about to');
    $('#mytable').DataTable( { "searching": true, "pageLength": 25,  "lengthMenu": [ [10, 25, 50, -1], [10, 25, 50, "All"] ] } );
    console.log('test');
} );
</script>


</body>
</html>
<? close_oracle() ?>
